# Nome da aplicação
spring.application.name=api-leitura

# Configurações de conexão com o banco H2
spring.datasource.url=jdbc:h2:mem:leituradb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mostra o SQL no console para você ver o Spring criando as tabelas
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cria e atualiza as tabelas automaticamente com base nas suas classes @Entity
spring.jpa.hibernate.ddl-auto=update

# Habilita a interface visual do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console